site_name: DBMS Documentation
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Tutorials:
      - Quick Start: tutorials/quickstart.md
      - First SQL Query: tutorials/first-query.md
      - Building Complex Queries: tutorials/complex-queries.md
  - How-to Guides:
      - Installation: how-to/installation.md
      - Running Tests: how-to/testing.md
      - Debugging Queries: how-to/debugging.md
      - Extending the Parser: how-to/extending-parser.md
      - Parse Tree Visualization: how-to/parse-trees.md
  - API Reference:
      - Overview: api/index.md
      - Parser: api/parser.md
      - Storage: api/storage.md
      - Executor: api/executor.md
      - Logging: api/logging.md
      - Client: api/client.md
  - Explanation:
      - Architecture Overview: explanation/architecture.md
      - SQL Parser Deep Dive: explanation/parser.md
      - Grammar Reference: explanation/grammar.md
      - Storage System: explanation/storage.md
      - Query Execution: explanation/execution.md
      - Configuration: explanation/configuration.md
      - Logging Strategy: explanation/logging.md
      - SQL Features: sql_features.md
  - Contributing: contributing.md
theme:
  name: material
  palette:
    - scheme: slate  # dark mode by default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.prune
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.progressbar
  - pymdownx.arithmatex
