site_name: DBMS Documentation
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Architecture: architecture.md
  - Storage Backend: storage.md
  - Logging: logging.md
  - Contributing: contributing.md
  - API Reference:
      - Overview: api/index.md
      - Storage: api/storage.md
      - Executor: api/executor.md
      - Logging: api/logging.md
      - Client: api/client.md
      - Parser: api/parser.md
theme:
  name: material
  palette:
    - scheme: slate  # dark mode by default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - navigation.instant
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.progressbar
  - pymdownx.arithmatex
